// Generated by CoffeeScript 1.3.3
/*
# chromext
# chrome extension bootstrap with coffee, jade and stylus
# http://github.com/saschagehlich/chromext
#
# Copyright (c) 2012 FILSH Media GmbH <contact@filshmedia.net>
# MIT Licensed
*/

var chromext, logger, optparse, parser;

chromext = require('./chromext');

optparse = require('optparse');

parser = new optparse.OptionParser([]);

logger = global.logger = require('./lib/logger');

parser.banner = 'Usage: chromext <command>\n\nwhere <command> is one of:\n    build, init, watch';

parser.on(2, function(opt) {
  switch (opt) {
    case 'init':
      return chromext.init();
    case 'build':
      return chromext.build();
    case 'watch':
      return chromext.watch();
    default:
      return console.log(parser.toString());
  }
});

if (process.argv.length < 3) {
  console.log(parser.toString());
}

parser.parse(process.argv);
