// Generated by CoffeeScript 1.3.3
/*
# chromext
# chrome extension bootstrap with coffee, jade and stylus
# http://github.com/saschagehlich/chromext
#
# Copyright (c) 2012 FILSH Media GmbH <contact@filshmedia.net>
# MIT Licensed
*/

var exec, fs, path, _;

fs = require('fs');

path = require('path');

exec = require('child_process').exec;

_ = require('underscore');

_.str = require('underscore.string');

module.exports = function() {
  var buildPath, cwd, destFile, manifest, proc, stderr;
  buildPath = process.argv[3] ? path.resolve(process.cwd(), process.argv[3]) : process.cwd();
  if (!fs.existsSync(path.resolve(buildPath, 'manifest.json'))) {
    return logger.error('error', buildPath + ' was not recognized as a chromext workspace');
  }
  manifest = require(path.resolve(buildPath, 'manifest.json'));
  destFile = _.str.slugify(manifest.name) + '-' + manifest.version + '.zip';
  logger.log('zip', 'Packing archive ' + destFile);
  cwd = process.cwd();
  process.chdir(buildPath);
  proc = exec('zip -0 -r ' + destFile + ' manifest.json js css assets *.html');
  process.chdir(cwd);
  stderr = "";
  proc.stderr.on('data', function(data) {
    return stderr += data;
  });
  return proc.on('exit', function(code) {
    if (code === 0) {
      return logger.log('zip', '.zip has successfully been created: ' + path.resolve(buildPath, destFile));
    } else {
      logger.error('zip', destFile + ' could not be created!');
      console.log("");
      return console.log(stderr);
    }
  });
};
