// Generated by CoffeeScript 1.3.3
/*
# chromext
# chrome extension bootstrap with coffee, jade and stylus
# http://github.com/saschagehlich/chromext
#
# Copyright (c) 2012 FILSH Media GmbH <contact@filshmedia.net>
# MIT Licensed
*/

var fs, path, watcher;

fs = require('fs');

path = require('path');

watcher = require('./watcher');

module.exports = function() {
  var coffeeWatcher, jadeWatcher, stylusWatcher, watchPath;
  watchPath = process.argv[3] ? path.resolve(process.cwd(), process.argv[3]) : process.cwd();
  if (!fs.existsSync(path.resolve(watchPath, 'manifest.json'))) {
    return logger.error('error', watchPath + ' was not recognized as a chromext workspace');
  }
  logger.log('info', 'Initializing watchers...');
  coffeeWatcher = new watcher.coffee(path.resolve(watchPath, 'coffee'), path.resolve(watchPath, 'js'));
  jadeWatcher = new watcher.jade(watchPath, watchPath);
  return stylusWatcher = new watcher.stylus(path.resolve(watchPath, 'stylus'), path.resolve(watchPath, 'css'));
};
